server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/revplay_playlists?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET:8f434346648f6b96bc89ca248d101297e201b1cb42bd205f31a26d70fb90737a}
